%-----------------------------------------------------------------------
% Job saved on 12-Apr-2024 18:21:58 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
%%
matlabbatch{1}.spm.temporal.st.scans = {
                                        {
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,1'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,2'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,3'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,4'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,5'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,6'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,7'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,8'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,9'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,10'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,11'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,12'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,13'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,14'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,15'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,16'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,17'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,18'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,19'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,20'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,21'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,22'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,23'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,24'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,25'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,26'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,27'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,28'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,29'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,30'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,31'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,32'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,33'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,34'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,35'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,36'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,37'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,38'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,39'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,40'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,41'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,42'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,43'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,44'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,45'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,46'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,47'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,48'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,49'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,50'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,51'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,52'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,53'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,54'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,55'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,56'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,57'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,58'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,59'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,60'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,61'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,62'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,63'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,64'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,65'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,66'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,67'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,68'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,69'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,70'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,71'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,72'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,73'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,74'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,75'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,76'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,77'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,78'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,79'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,80'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,81'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,82'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,83'
                                        '/home/matay/spmbasics/data/MoAEpilot/sub-01/func/rsub-01_task-auditory_bold.nii,84'
                                        }
                                        }';
%%
matlabbatch{1}.spm.temporal.st.nslices = 64;
matlabbatch{1}.spm.temporal.st.tr = 7;
matlabbatch{1}.spm.temporal.st.ta = 6.8906;
matlabbatch{1}.spm.temporal.st.so = [64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1];
matlabbatch{1}.spm.temporal.st.refslice = 32;
matlabbatch{1}.spm.temporal.st.prefix = 'a';
